jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Create empty JS builddir
        run: |2
            mkdir js/app/build
            touch js/app/build/index.html
      - name: Install stable toolchain
        uses: "actions-rs/toolchain@v1"
        with:
          override: 'true'
          profile: minimal
          toolchain: '1.54.0'
      - name: Run cargo test
        uses: "actions-rs/cargo@v1"
        with:
          command: test
name: Test Rust
on:
  push: {}
